### ISSUE TITLE
Use UniversalElectricity for the Electric Fences

### ISSUE THREAD

**Issue by keplersj** [tyrope/fencing#21] opened 2014-02-02 04:39 UTC
`Repo owner edit: We'll be supporting Thermal Expansion's Redstone Flux instead of UE.`

**Comment by tyrope** [comment] 2014-02-02 08:27
Personally not a fan of universal electricity. But will give it a shot if you can provide an api.

**Comment by keplersj** [comment] 2014-02-02 19:02
The [Universal Electricity API](http://universalelectricity.com) is an annotation-based API that works with all the major Minecraft Power Networks for you. And it allows for easy building with Gradle, so that you don't need to contain the API in your repo.

**Comment by tyrope** [comment] 2014-02-02 19:18
Reading the API this will require a complete rewrite of the electric fences, including how it's loaded. Marking as Low Priority, patches welcome.

**Comment by keplersj** [comment] 2014-02-02 19:20
Yeah… I was worried about that.

**Comment by tyrope** [comment] 2014-04-02 13:28
Confirmed for Fencing 0.6 / MC1.8

**Comment by tyrope** [comment] 2014-04-26 03:51
Due to the developments at [feed the beast](http://forum.feed-the-beast.com/threads/update-on-the-future-of-ftb-modpacks-in-1-7.44850/) Fencing will only support RF in future minecraft versions.

**Comment by keplersj** [comment] 2014-04-26 04:38
Sounds like a smart decision to me. If you need any help in the transition just ask.

**Comment by tyrope** [comment] 2014-05-11 12:51
Closed in favour of #25.

**Closed as completed by tyrope** 2014-05-11 12:51 UTC
Labels: Feature
